##Non Graded Challenge 5
Assignment Instructions

---




*   Buatlah Tensor dibawah ini dengan Python:


$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \\ 7 & 12 \\ \end{bmatrix} \begin{bmatrix} 57 & 67 \\ 99 & 43 \end{bmatrix} \ \begin{bmatrix} 75 & 21 \\ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \\ 18 & 84 \end{bmatrix} \end{bmatrix} $$

* Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \\ 22 \\ 19 \end{bmatrix} $$

* Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix} $$

Assignment Objectives

---


Non-Graded Assignment ini dibuat guna mengevaluasi konsep Linear Algebra sebagai berikut:

* Memahami konsep Matrices and Tensors
* Mampu membuat Matrices dan Tensor dengan Python
* Mampu menerapkan operasi aritmatika terhadap Matrices

In [1]:
import numpy as np

In [25]:
T = np.array([
    [[[23, 50], [7, 12]], [[57, 67], [99, 43]]],
    [[[75, 21], [57, 12]], [[87, 26], [18, 84]]]
])
print(T.shape)
print(T)

(2, 2, 2, 2)
[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


In [24]:
#Multiply Matrix
A = np.array([
    [23, 50, 19], 
    [7, 12, 109], 
    [57, 67, 98]
])

B = np.array([17, 22, 19])
print('A:\n',A)
print('B:\n',B,'\n')
print('A*B adalah',A.dot(B))

A:
 [[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
B:
 [17 22 19] 

A*B adalah [1852 2454 4305]


In [14]:
#Transpose Matrix A
print(A.T)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [16]:
#Determinant Matrix A
print(np.linalg.det(A))

131344.0000000002


In [18]:
#Invers Matrix A
print(np.linalg.inv(A))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
