##Non Graded Challenge 6
Assignment Instructions

---


Apakah $\begin{bmatrix}1\\3\end{bmatrix}$ adalah eigenvector dari $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$? 

Jika iya, berapakah eigenvalue-nya?


Assignment Objectives

---


Non-Graded Assignment ini dibuat guna mengevaluasi konsep Linear Algebra sebagai berikut:

* Memahami konsep eigenvalue dan eigenvector
* Dapat mencari eigenvalue dan eigenvector

In [1]:
import numpy as np

In [8]:
A = np.array([
    [1, -1],
    [6, -4]
])
v = np.array([1, 3])
print('A:\n',A)
print('v:\n',v)

A:
 [[ 1 -1]
 [ 6 -4]]
v:
 [1 3]


In [10]:
#Melihat apakah vektor v merupakan eigenvector dari matriks A
Av = A@v
Av

array([-2, -6])

In [11]:
-2 * v

array([-2, -6])

Artinya vektor v merupakan eigenvector dari matriks A